version: '3.3'

services:
   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       - wordpress_files:/var/www/html
       - ${PWD}/wordpress.ini:/usr/local/etc/php/conf.d/wordpress.ini 
     ports:
       - "80:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wpuser 
       WORDPRESS_DB_PASSWORD: durkness
       WORDPRESS_DB_NAME: woo

   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: durkness1 
       MYSQL_DATABASE: woo 
       MYSQL_USER: wpuser 
       MYSQL_PASSWORD: durkness 
volumes:
    wordpress_files:
    db_data:
